### ISSUE TITLE
reduce Katip level messages to Infos instead of Warnings for non Errors

### ISSUE THREAD

**Issue by fredericcogny** [novadiscovery/hmatrix-sundials#1]
https://github.com/novadiscovery/hmatrix-sundials/blob/a9271e83b95051a57ec868eb1b9cf6fee8d23c3a/src/Numeric/Sundials/Common.hs#L421

**Comment by avandecreme** [comment]
This was fixed in https://github.com/novadiscovery/hmatrix-sundials/commit/19b492efaa3f0b869bf64a36e0fdf899a4049cf1
